#include <stdio.h>

int main () {
	
float ENTRADA, MEDIA_POSITIVOS = 0, MEDIADOSNOMECOMPLEXOKKKKKKKJESUSPROFESSORNAORIPF = 0;
int i, POSITIVOS = 0;
for (i = 0; i < 6; i++){
  scanf("%f", &ENTRADA);
  if (ENTRADA > 0){
    POSITIVOS++;
    MEDIADOSNOMECOMPLEXOKKKKKKKJESUSPROFESSORNAORIPF += ENTRADA;

  }
}
MEDIA_POSITIVOS = MEDIADOSNOMECOMPLEXOKKKKKKKJESUSPROFESSORNAORIPF/POSITIVOS;
printf("%d valores positivos\n", POSITIVOS);
printf("%.1f\n", MEDIA_POSITIVOS);
return 0;
}